/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengembalian;

import authentiocation.*;
import buku.*;
import peminjaman.*;
import siswa.*;
import utils.*;

/**
 *
 * @author Farhan Fadila
 */
public class FormDetailPengembalian extends javax.swing.JFrame {
    
    
    private final AuthenticationController authenticationController = new AuthenticationController();
    private final PeminjamanController peminjamanController = new PeminjamanController();
    private final PengembalianController pengembalianController = new PengembalianController();
    private final BukuController bukuController = new BukuController();
    private final SiswaController siswaController = new SiswaController();
    
    private DisableEditTableModel model;
    private final Utils utils = new Utils();
    
    private String idPengembalian;

    /**
     * Creates new form FormDetailPengembalian
     */
    public FormDetailPengembalian(String idPengembalian) {
        initComponents();
        this.idPengembalian = idPengembalian;
        getDetailPengembalian();
    }
    
    private void getDetailPengembalian() {
        try {
            Pengembalian pengembalian = pengembalianController.detail(idPengembalian);
            
            initTopSection(pengembalian.nisn);
            initBottomSection(pengembalian);
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void initTopSection(String nisn) {
        try {
            Siswa siswa = siswaController.detail(nisn);
            
            lbl_nisn.setText(nisn);
            lbl_nama.setText(siswa.namaSiswa);
            lbl_kelas.setText(siswa.kelas);
            lbl_telepon.setText(siswa.telepon);
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }
    
     private void initBottomSection(Pengembalian pengembalian) {
        try {
            Peminjaman peminjaman = peminjamanController.detail(pengembalian.idPeminjaman);
            User adminPinjam = authenticationController.detail(peminjaman.idAdminPinjam);
            User adminPengembalian = authenticationController.detail(pengembalian.idAdminPengembalian);
            
            lbl_denda.setText(utils.formatToRupiah(pengembalian.denda));
            lbl_lama_pinjam.setText(String.valueOf(pengembalian.lamaPinjam));
            lbl_tanggal.setText(peminjaman.tanggalPinjam + " - " + pengembalian.tanggalPengembalian);
            lbl_admin_pinjam.setText(adminPinjam.username);
            lbl_admin_pengembalian.setText(adminPengembalian.username);
            
            initColumnTabel();
            initRowTabel(peminjaman.idBuku, peminjaman.jumlah);
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }
     
     
     private void initColumnTabel() {
        model = new DisableEditTableModel();
        
        tbl_buku.setModel(model);
        
        model.addColumn("No");
        model.addColumn("ID Buku");
        model.addColumn("Buku");
        model.addColumn("Jumlah");
    }
     
    private void initRowTabel(
            String idBukuArrayString, 
            String jumlahArrayString) {
        try {
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
            String[] idBuku = idBukuArrayString.split(",");
            String[] jumlahBuku = jumlahArrayString.split(",");
                    
            for(int i = 0; i < idBuku.length; i++) {
                Object[] obj = new Object[4];
                Buku buku = bukuController.detail(idBuku[i]);

                obj[0] = i + 1;
                obj[1] = buku.idBuku;
                obj[2] = buku.judul;
                obj[3] = jumlahBuku[i];
                model.addRow(obj); 
            }
               
        } catch(Exception ex) {
            System.out.println("initRowTabel ERROR" + ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_buku = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_nisn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_kelas = new javax.swing.JLabel();
        lbl_telepon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_denda = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_lama_pinjam = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        lbl_admin_pinjam = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_admin_pengembalian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_ok.setBackground(new java.awt.Color(51, 153, 255));
        btn_ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("OK");
        btn_ok.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok.setBorderPainted(false);
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_okMousePressed(evt);
            }
        });
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Detail Pengembalian");

        tbl_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_buku);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Buku");

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("NISN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Kelas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nama");

        lbl_nisn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_nisn.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Telepon");

        lbl_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_nama.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        lbl_kelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_kelas.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        lbl_telepon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_telepon.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_telepon)
                    .addComponent(lbl_kelas)
                    .addComponent(lbl_nama)
                    .addComponent(lbl_nisn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_nisn))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_nama))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_kelas))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_telepon))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(244, 244, 244));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Denda");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Lama Pinjam");

        lbl_denda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_denda.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Admin Pinjam");

        lbl_lama_pinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_lama_pinjam.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        lbl_tanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_tanggal.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        lbl_admin_pinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_admin_pinjam.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Admin Pengembalian");

        lbl_admin_pengembalian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_admin_pengembalian.setText("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_admin_pinjam)
                    .addComponent(lbl_tanggal)
                    .addComponent(lbl_lama_pinjam)
                    .addComponent(lbl_denda)
                    .addComponent(lbl_admin_pengembalian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_denda))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_lama_pinjam))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_tanggal))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_admin_pinjam))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_admin_pengembalian))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(139, 139, 139))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
        
    }//GEN-LAST:event_btn_okMouseClicked

    private void btn_okMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMousePressed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_okMousePressed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_admin_pengembalian;
    private javax.swing.JLabel lbl_admin_pinjam;
    private javax.swing.JLabel lbl_denda;
    private javax.swing.JLabel lbl_kelas;
    private javax.swing.JLabel lbl_lama_pinjam;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nisn;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JLabel lbl_telepon;
    private javax.swing.JTable tbl_buku;
    // End of variables declaration//GEN-END:variables
}
