/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengembalian;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import laporan.FormPilihTanggalLaporan;
import siswa.*;
import utils.*;

/**
 *
 * @author Farhan Fadila
 */
public class FormPengembalian extends javax.swing.JFrame {
    private final PengembalianController pengembalianController = new PengembalianController();
    private final SiswaController siswaController = new SiswaController();
    
    private DisableEditTableModel model;
    private final Utils utils = new Utils();

    /**
     * Creates new form FormPengembalian
     */
    public FormPengembalian() {
        initComponents();
        initColumnTabel();
        initRowTabel();
        listenSearch();
        setExtendedState(JFrame.MAXIMIZED_BOTH);   
    }
    
    private void initColumnTabel() {
        model = new DisableEditTableModel();
        
        tbl_pengembalian.setModel(model);
        model.addColumn("No");
        model.addColumn("ID Pengembalian");
        model.addColumn("NISN");
        model.addColumn("Siswa");
        model.addColumn("Denda");
        model.addColumn("Lama Pinjam");
        model.addColumn("Tanggal Pengembalian");
    }
    
    private void initRowTabel() {
        try {
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
            List<Pengembalian> data = pengembalianController.data();
            
            for(int i = 0; i < data.size(); i++) {
               Object[] obj = new Object[7];
               Pengembalian item = data.get(i);
               Siswa siswa = siswaController.detail(item.nisn);
               
               obj[0] = i + 1;
               obj[1] = item.idPengembalian;
               obj[2] = item.nisn;
               obj[3] = siswa.namaSiswa;
               obj[4] =  utils.formatToRupiah(item.denda);
               obj[5] = String.valueOf(item.lamaPinjam) + " hari";
               obj[6] = item.tanggalPengembalian;
               
               model.addRow(obj); 
            } 
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void listenSearch() {
        txt_search.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
               onSearch();
            }
            public void removeUpdate(DocumentEvent e) {
                onSearch();
            }
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }
    
    private void onSearch() {
        try {
            String query = txt_search.getText();
            
            if(query.isEmpty()) {
                initRowTabel();
                return;
            }
            
            List<Pengembalian> data = pengembalianController.search(query);
           
            
            fillRow(data);
        } catch(Exception ex) {
            System.out.println("onSearch ex" + ex);
        }
    }
    
    private void fillRow(List<Pengembalian> data) {
         try {
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
            for(int i = 0; i < data.size(); i++) {
               Object[] obj = new Object[7];
               Pengembalian item = data.get(i);
               Siswa siswa = siswaController.detail(item.nisn);
               
               obj[0] = i + 1;
               obj[1] = item.idPengembalian;
               obj[2] = item.nisn;
               obj[3] = siswa.namaSiswa;
               obj[4] =  utils.formatToRupiah(item.denda);
               obj[5] = String.valueOf(item.lamaPinjam) + " hari";
               obj[6] = item.tanggalPengembalian;
               
               model.addRow(obj); 
            } 
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengembalian = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        lbl_pinjam = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pengembalian);

        txt_search.setPreferredSize(new java.awt.Dimension(59, 24));

        jLabel1.setText("Cari");

        btn_ok.setBackground(new java.awt.Color(51, 153, 255));
        btn_ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("OK");
        btn_ok.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok.setBorderPainted(false);
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_okMousePressed(evt);
            }
        });

        lbl_pinjam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_pinjam.setText("Pengembalian");

        btn_laporan.setBackground(new java.awt.Color(204, 204, 0));
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Laporan");
        btn_laporan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_laporan.setBorderPainted(false);
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_laporanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_pinjam)
                                .addGap(528, 528, 528)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_pinjam))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMousePressed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_okMousePressed

    private void tbl_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pengembalianMouseClicked
       try {
            int selectedRow = tbl_pengembalian.getSelectedRow();
        
            if (selectedRow <= -1) {
                throw new Exception("Silahkan pilih salah satu data di tabel terlebih dahulu");
            }
            
            String idPengembalian = model.getValueAt(selectedRow, 1).toString();
            
            JFrame frame = new FormDetailPengembalian(idPengembalian);
            
            frame.setVisible(true);
       } catch(Exception ex) {
           System.out.println(ex);
       }
    }//GEN-LAST:event_tbl_pengembalianMouseClicked

    private void btn_laporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMousePressed
        JFrame frame = new FormPilihTanggalLaporan("Laporan Pengembalian", "laporan_pengembalian");
        
        frame.setVisible(true);
    }//GEN-LAST:event_btn_laporanMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_pinjam;
    private javax.swing.JTable tbl_pengembalian;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
