/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import authentiocation.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kategori.FormKategori;
import rak.FormRak;
import buku.FormBuku;
import siswa.FormSiswa;
import transaction.FormPeminjaman;
import transaction.FormPinjam;

/**
 *
 * @author Farhan Fadila
 */
public class HomePage extends javax.swing.JFrame {
    final AuthenticationController authenticationController = new AuthenticationController();
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    
    
    private void navigasi(String menu) {
       JFrame frame;
       
        switch(menu) {
            case "kategori":
                frame = new FormKategori();
                break;
            case "buku":
                frame = new FormBuku();
                break;
            case "siswa":
                frame = new FormSiswa();
                break;
            case "peminjaman":
                frame = new FormPeminjaman();
                break;
            case "pinjam":
                frame = new FormPinjam();
                break;
            default:
                frame = new FormRak();
        }
        
       frame.setAlwaysOnTop(true);
       frame.setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        ic_buku = new javax.swing.JLabel();
        ic_pinjam = new javax.swing.JLabel();
        ic_rak = new javax.swing.JLabel();
        ic_kategori = new javax.swing.JLabel();
        ic_siswa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        parent.setBackground(new java.awt.Color(255, 255, 255));
        parent.setMinimumSize(new java.awt.Dimension(1024, 768));
        parent.setPreferredSize(new java.awt.Dimension(1024, 768));

        ic_buku.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ic_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_buku.png"))); // NOI18N
        ic_buku.setText("Buku");
        ic_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_bukuMousePressed(evt);
            }
        });

        ic_pinjam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ic_pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_pinjam.png"))); // NOI18N
        ic_pinjam.setText("Pinjam");
        ic_pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_pinjamMousePressed(evt);
            }
        });

        ic_rak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ic_rak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_rak.png"))); // NOI18N
        ic_rak.setText("Rak");
        ic_rak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_rakMousePressed(evt);
            }
        });

        ic_kategori.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ic_kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_kategori.png"))); // NOI18N
        ic_kategori.setText("Kategori");
        ic_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_kategoriMousePressed(evt);
            }
        });

        ic_siswa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ic_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_siswa.png"))); // NOI18N
        ic_siswa.setText("Siswa");
        ic_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_siswaMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 900));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menu Aplikasi Perpustakaan");

        javax.swing.GroupLayout parentLayout = new javax.swing.GroupLayout(parent);
        parent.setLayout(parentLayout);
        parentLayout.setHorizontalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(parentLayout.createSequentialGroup()
                .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parentLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel1))
                    .addGroup(parentLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ic_siswa)
                            .addComponent(ic_pinjam))
                        .addGap(60, 60, 60)
                        .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ic_buku)
                            .addComponent(ic_rak))
                        .addGap(60, 60, 60)
                        .addComponent(ic_kategori)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        parentLayout.setVerticalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parentLayout.createSequentialGroup()
                        .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ic_pinjam)
                            .addComponent(ic_buku))
                        .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parentLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(ic_siswa))
                            .addGroup(parentLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(ic_rak))))
                    .addGroup(parentLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(ic_kategori)))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        final boolean logout = authenticationController.logout();

        if(logout) {
            JFrame login = new FormLogin();
            dispose();
            login.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Logout");
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void ic_siswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_siswaMousePressed
        navigasi("siswa");
    }//GEN-LAST:event_ic_siswaMousePressed

    private void ic_kategoriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_kategoriMousePressed
        navigasi("kategori");
    }//GEN-LAST:event_ic_kategoriMousePressed

    private void ic_rakMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_rakMousePressed
        navigasi("rak");
    }//GEN-LAST:event_ic_rakMousePressed

    private void ic_pinjamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_pinjamMousePressed
        navigasi("pinjam");
    }//GEN-LAST:event_ic_pinjamMousePressed

    private void ic_bukuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_bukuMousePressed
        navigasi("buku");
    }//GEN-LAST:event_ic_bukuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ic_buku;
    private javax.swing.JLabel ic_kategori;
    private javax.swing.JLabel ic_pinjam;
    private javax.swing.JLabel ic_rak;
    private javax.swing.JLabel ic_siswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel parent;
    // End of variables declaration//GEN-END:variables
}
